development: 
  encoding: unicode
  adapter: postgresql
  username: mileage
  port: 5432
  database: mileage_development
#  password: password
#  host: hostname

production: 
  encoding: unicode
  adapter: postgresql
  username: mileage
  port: 5432
  database: mileage_production
#  password: password
#  host: hostname

test: 
  encoding: unicode
  adapter: postgresql
  username: mileage
  port: 5432
  database: mileage_test
#  password: password
#  host: hostname
